language: python
python:
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install pylint
  # - pip install nose
script:
  - pylint --errors-only website
  - pylint --errors-only server
  # - nosetests
  # - ./manage.py test
